2023-05-19 17:50:13,081  ERROR       send_post.py  run  frame_192.168.0.19 is not update
2023-05-23 11:32:33,645  ERROR       send_post.py  run  HTTPConnectionPool(host='0.0.0.0', port=9617): Max retries exceeded with url: /test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faff01972b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2023-05-23 11:32:38,653  ERROR       send_post.py  run  HTTPConnectionPool(host='0.0.0.0', port=9617): Max retries exceeded with url: /test (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faff0140040>: Failed to establish a new connection: [Errno 111] Connection refused'))
